### ISSUE TITLE
status of eggwn qt5 port

### ISSUE THREAD

**Issue by mckaygerhard** [xiangzhai/eggwm#1]
i have try to compile and get some erros, fixed with newer instalation of qt4.. 

do u wish mantain this proyect or only was a try?

i do not see many commit about corrections, only port and then paused the work on the proyect

**Comment by hagabaka** [comment]
On Arch Linux when building against Qt5 I get this error:
```
g++ -c -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt/mkspecs/linux-g++ -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -Ibuild -o build/Main.o src/eggwm/Main.cpp
In file included from ./src/eggwm/EggWM.h:20:0,
                 from src/eggwm/Main.cpp:14:
./src/eggwm/util/Include.h:28:24: fatal error: QX11Info: No such file or directory
     #include <QX11Info>
                        ^
compilation terminated.
Makefile:783: recipe for target 'build/Main.o' failed
make: *** [build/Main.o] Error 1
```
Changing the include path to `<QtX11Extras/QX11Info>` gets through this, but then I'll get
```
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1 -o eggwm build/Main.o build/EggWM.o build/CreateNotifyHandler.o build/DestroyNotifyHandler.o build/UnmapNotifyHandler.o build/MapRequestHandler.o build/ConfigureRequestHandler.o build/ButtonPressHandler.o build/ClientMessageHandler.o build/EventFactory.o build/XWindowList.o build/XWindow.o build/Client.o build/ClientFrame.o build/Config.o build/ICCCM.o build/EWMHRoot.o build/WMCheckWindow.o build/EWMHClient.o build/AtomList.o build/moc_XWindow.o build/moc_ClientFrame.o   -lX11 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
build/EggWM.o: In function `EggWM::EggWM(int, char**)':
EggWM.cpp:(.text+0x350): undefined reference to `QX11Info::appScreen()'
EggWM.cpp:(.text+0x357): undefined reference to `QX11Info::appRootWindow(int)'
EggWM.cpp:(.text+0x35f): undefined reference to `QX11Info::display()'
EggWM.cpp:(.text+0x374): undefined reference to `QX11Info::display()'
build/ClientMessageHandler.o: In function `ClientMessageHandler::processEvent(_XEvent*)':
ClientMessageHandler.cpp:(.text+0x23f): undefined reference to `QX11Info::display()'
build/XWindowList.o: In function `XWindowList::restackWindows() const':
XWindowList.cpp:(.text+0x122): undefined reference to `QX11Info::display()'
build/XWindow.o: In function `XWindow::bypassWM() const':
XWindow.cpp:(.text+0x130): undefined reference to `QX11Info::display()'
build/XWindow.o:XWindow.cpp:(.text+0x5fe): more undefined references to `QX11Info::display()' follow
build/EWMHRoot.o: In function `EWMHRoot::changeProperty(unsigned long, unsigned long, unsigned char const*, int) const':
EWMHRoot.cpp:(.text+0x25): undefined reference to `QX11Info::appScreen()'
EWMHRoot.cpp:(.text+0x2c): undefined reference to `QX11Info::appRootWindow(int)'
EWMHRoot.cpp:(.text+0x34): undefined reference to `QX11Info::display()'
build/EWMHRoot.o: In function `EWMHRoot::sendDesktopNames(QString const&) const':
EWMHRoot.cpp:(.text+0x643): undefined reference to `QX11Info::appScreen()'
EWMHRoot.cpp:(.text+0x64a): undefined reference to `QX11Info::appRootWindow(int)'
EWMHRoot.cpp:(.text+0x656): undefined reference to `QX11Info::display()'
build/WMCheckWindow.o: In function `WMCheckWindow::WMCheckWindow()':
WMCheckWindow.cpp:(.text+0xc4): undefined reference to `QX11Info::display()'
build/EWMHClient.o: In function `EWMHClient::getProperty(unsigned long, unsigned long, unsigned char**, unsigned long*, long, long) const':
EWMHClient.cpp:(.text+0x52): undefined reference to `QX11Info::display()'
build/AtomList.o: In function `AtomList::AtomList()':
AtomList.cpp:(.text+0xa2): undefined reference to `QX11Info::display()'
collect2: error: ld returned 1 exit status
Makefile:335: recipe for target 'eggwm' failed
make: *** [eggwm] Error 1
```

**Comment by hagabaka** [comment]
OK, instead of editing the #include path, changing `greaterThan(QT_MAJOR_VERSION, 5)` to `greaterThan(QT_MAJOR_VERSION, 5)` also fixes the include error. It doesn't fix the undefined reference errors though.

**Comment by xiangzhai** [comment]
Hi @hagabaka thanks for your patch ;)

**Comment by mckaygerhard** [comment]
hi @hagabaka i download and test with qt 4.6.3 and 4.7.4 and in both compiled

i not tested yet, but almost compiled fine.

but i not close the issue,due the question are :  "What are tyhe status of this folk, do u mantain it?"

for now, its partially anwered: compiled in qt4, and in qt5, but will be mantained? maybe this are fine for the moonlight desktop as window manager, do u insteres in join forces with ?

**Comment by mckaygerhard** [comment]
hi @xiangzhai i tested the wm with the patch and works in qt4 and qt5, some problems still happened (of course its a recent folk)

but the project status?, but will be mantained? maybe this are fine for the moonlight desktop as window manager, do u insteres in join forces with

**Comment by xiangzhai** [comment]
Hi @mckaygerhard 

I will fix some issue such as mwHint during my winter`s holiday, and the project status is not maintained, I just try to be familiar with Xlib protocol ;) the same purpose projects are xtk https://github.com/xiangzhai/xtk && xpanel https://github.com/xiangzhai/xpanel

What is moonlight desktop? There are lxqt && razor-qt forked in your repositories, and can you show me some URL to me? thanks a lot!

Regards,
Leslie Zhai

**Comment by mckaygerhard** [comment]
well, i noted u have more concentrate to recover experience to work in kde devel right?

ok moonlight desktop have importnat hard differences:

# internal app comunications are more faster, due uses a microservices 
# try to save more ram and cpu cicles rather than /yet) lxqt in top of qt5 framework
# future try to cover embebed devices and tables (far far future very far), lxqt does not

moonlight uses microcpp services and its in very early stages, main README.md of core repo have some urls for u, specially the low traficc mail list

now i can close the issue, app its unmantained but open to contributions and receive sporadically fixeds from u...
